### 学习cs231n官方提供的numpy教程

In [2]:
import numpy as np
a = np.array([1, 2])
b = np.array([[1, 2], [3, 4]])
print(a)
print(b)
print(b.shape)

[1 2]
[[1 2]
 [3 4]]
(2, 2)


使用切片

In [3]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

print(a[0, 1])
b[0,0] = 77
# 意味着a[0,1]=77

print(a[0, 1])

2
77


In [4]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

row_1 = a[1, :]
row_2 = a[1:2, :]
# 两种是有区别的
print(row_1, row_1.shape)
print(row_2, row_2.shape)

col_1 = a[:, 1]
col_2 = a[:, 1:2]

print(col_1, col_1.shape)
print(col_2, col_2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [9]:
a = np.array([[1, 2], [3, 4], [5, 6]])

print(a.shape)
print(a)
# 整数索引 获得 0,0  1,1  2,0 三个位置的数
print(a[[0, 1, 2], [0, 1, 0]])
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

print(a[[0, 0], [1, 1]])
print(np.array([a[0, 1], a[0, 1]]))

(3, 2)
[[1 2]
 [3 4]
 [5 6]]
[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [12]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

b = np.array([0, 2, 0, 1])
print(b)

print(a[np.arange(4), b])

a[np.arange(4), b] += 10
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[0 2 0 1]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


布尔索引
数组 + 索引 输出秩为1且索引为true的数

In [15]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)

print(bool_idx)

print(a[bool_idx])

print(a[a>2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


每个 numpy 数组都是相同类型元素的grid。 Numpy 提供了大量可用于构造数组的数据类型。

Numpy 会在您创建数组时尝试猜测数据类型，但构造数组的函数通常还包含一个可选参数以显式指定数据类型。

In [16]:
x = np.array([1, 2])
print(x.dtype)

x = np.array([1.0, 2.0])
print(x.dtype)

x = np.array([1, 2], dtype=np.int64)
print(x.dtype)

int32
float64
int64


对数组的常用数学公式

In [21]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print(x + y)
print(np.add(x, y))

print(x - y)
print(np.subtract(x, y))

# 不是向量乘法
print(x * y)
print(np.multiply(x, y))

print(x/y)
print(np.divide(x, y))

print(np.sqrt(x))

# 矩阵乘法
print(x.dot(y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[19. 22.]
 [43. 50.]]


In [29]:
x = np.array([[1, 2], [3, 4]])
print(x)

print(np.sum(x)) #计算所有的元素和
print(np.sum(x, axis=0)) #计算列一级
print(np.sum(x, axis=1)) #计算行一级



y = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print(y)
print(y.shape)

print(np.sum(y))
print(np.sum(y, axis=0))
print(np.sum(y, axis=0).shape)
print(np.sum(y, axis=1))
print(np.sum(y, axis=2))

[[1 2]
 [3 4]]
10
[4 6]
[3 7]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
(3, 2, 2)
78
[[15 18]
 [21 24]]
(2, 2)
[[ 4  6]
 [12 14]
 [20 22]]
[[ 3  7]
 [11 15]
 [19 23]]


广播： 可以在执行运算操作的时候处理不同大小的数组

In [40]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

print(x)
print(v)
print("")
#我们想要x的每一行都加上v
y = np.empty_like(x)

#使用loop
for i in range(4):
    y[i] = x[i] + v
    print(y[i])


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 0 1]

[2 2 4]
[5 5 7]
[ 8  8 10]
[11 11 13]


当时当矩阵非常大的时候，这种循环操作会非常慢，注意到我们可以将v垂直堆叠后与x相加

In [41]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))
print(vv)

print(x + vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [42]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v

#自动广播
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


广播规则
- 如果两个数组的秩不相同，则在较低的数组前多增加一维，直到相同
- 如果两个数组在维度中有相同的大小，或者其中一个数组的维度大小为1，那么我们称这两个数组在维度上兼容
- 如果两个数组在所有维度上都兼容，那么它们两个可以广播
- 广播后，每个数组每一维都等于它们两个在这一维上的最大值
- 在某一个维度上，如果一个数组大小为1，另一个大于1，那么第一个数组就像在这个维度上复制一样

In [49]:
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)

print(np.reshape(v, (3, 1)))
print(np.reshape(v, (3, 1)) * w)

x = np.array([[1,2,3], [4,5,6]])
print(x + v)

print(x.T)
print(w)
print((x.T + w).T)



[[1]
 [2]
 [3]]
[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[1 4]
 [2 5]
 [3 6]]
[4 5]
[[ 5  6  7]
 [ 9 10 11]]
